server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: "0243"
    url: jdbc:postgresql://localhost:5432/LangForU
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  resources:
    static-locations: classpath:/static/

  mail:
    host: smtp.gmail.com
    port: 587
    username: langforu.softdev@gmail.com
    password: pijfrgacqjdkhttw

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

